<?php

namespace Room13\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{

    public function findCountries()
    {
        return $this->findByType(Location::TYPE_COUNTRY);
    }
}